# https://taskfile.dev
version: '3'

tasks:
  build:
    cmds:
      - mix wasm Firefly.Demo.Triangle > main.wat
      - wat2wasm main.wat -o main.wasm
      - firefly_cli build
  default:
    - task: build
